### ISSUE TITLE
做这个项目的动机是啥？

### ISSUE THREAD

**Issue by jinleileiking** [vaporz/turbo#28]
为啥不用grpc+grpc-gateway?

练手么？

**Comment by vaporz** [comment]
嗯，一开始是为了练手，刚接触go没几个月，这是我的第一个go程序，
另外grpc-gateway的问题还是挺多的，感觉不是很成熟

**Comment by jinleileiking** [comment]
这项目已经用于线上了么？我们准备入grpc-gateway坑。

**Comment by vaporz** [comment]
没有，work in progress，但正准备试用一下，
我们已经入了gateway的坑，确实。。。坑。。

**Comment by jinleileiking** [comment]
gateway 坑这么深？？。。。不敢用了。。。

**Comment by vaporz** [comment]
多调研吧，反正目前貌似没有上规模的正规公司在正式环境使用，也说不定你们的应用场景不会碰到那些坑。

**Comment by jinleileiking** [comment]
有啊。已经有很多应用了。google api和coreos都在用

**Comment by vaporz** [comment]
是嘛，但不知道他们用到什么程度，我感觉我这个项目也不错，66666

**Comment by jinleileiking** [comment]
咋联系你，加个微信？13820788636

**Comment by vaporz** [comment]
加你了
