### ISSUE TITLE
installation issue.

### ISSUE THREAD

**Issue by lzbj** [vaporz/turbo#34]
when I try to run glide install as the documentation.

I got the following problem:

glide install

[WARN]	The name listed in the config file (github.com/vaporz/turbo) does not match the current location (turbo)
[INFO]	Lock file (glide.lock) does not exist. Performing update.
[WARN]	The name listed in the config file (github.com/vaporz/turbo) does not match the current location (turbo)
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching updates for github.com/spf13/viper
[INFO]	--> Fetching updates for google.golang.org/grpc
[INFO]	--> Fetching updates for github.com/golang/protobuf
[INFO]	--> Fetching updates for github.com/bitly/go-simplejson
[INFO]	--> Fetching updates for github.com/gorilla/mux
[INFO]	--> Fetching updates for github.com/sirupsen/logrus
[INFO]	--> Fetching updates for github.com/fsnotify/fsnotify
[INFO]	--> Fetching updates for git.apache.org/thrift.git
[INFO]	--> Fetching updates for github.com/spf13/cobra
[INFO]	--> Fetching updates for github.com/stretchr/testify
[INFO]	--> Setting version for github.com/bitly/go-simplejson to da1a8928f709389522c8023062a3739f3b4af419.
[INFO]	--> Setting version for github.com/fsnotify/fsnotify to 4da3e2cfbabc9f751898f250b49f2439785783a1.
[INFO]	--> Setting version for github.com/gorilla/mux to 18fca31550181693b3a834a15b74b564b3605876.
[INFO]	--> Setting version for github.com/sirupsen/logrus to 68cec9f21fbf3ea8d8f98c044bc6ce05f17b267a.
[INFO]	--> Setting version for github.com/spf13/cobra to 99ff9334bda26384b5ef4a4aaa4d444d29bdde73.
[INFO]	--> Setting version for git.apache.org/thrift.git to 48ea3cde081b6343ceda2f1e3811887c1d11859b.
[INFO]	--> Setting version for github.com/spf13/viper to 0967fc9aceab2ce9da34061253ac10fb99bba5b2.
[INFO]	--> Setting version for github.com/stretchr/testify to f6abca593680b2315d2075e0f5e2a9751e3f431a.
[INFO]	--> Setting version for github.com/golang/protobuf to 5a0f697c9ed9d68fef0116532c6e05cfeae00e55.
[INFO]	--> Setting version for google.golang.org/grpc to d2a85bf7ad299df70daee28117f707025bddac22.
[INFO]	Resolving imports
[INFO]	--> Fetching updates for github.com/inconshreveable/mousetrap
[INFO]	--> Fetching updates for github.com/spf13/pflag
[ERROR]	Error scanning github.com/vaporz/turbo/turbo/cmd: cannot find package "." in:
	/Users/zhaoliu/Downloads/workspace/common/src/go/src/github.com/vaporz/turbo/turbo/turbo/cmd
[ERROR]	Failed to retrieve a list of dependencies: Error resolving imports

Is it expected?I think I should run glide install under:
github.com/vaporz/turbo, right?
in the doc, it's github.com/vaporz/turbo/turbo

**Comment by lzbj** [comment]
when I run make:

I got:

./server.go:11:2: cannot find package "git.apache.org/thrift.git/lib/go/thrift" in any of:

it it that I didn't get the package?

**Comment by lzbj** [comment]
I suggest change the dependency libs here:
https://github.com/apache/thrift

**Comment by vaporz** [comment]
> in the doc, it's github.com/vaporz/turbo/turbo
Fixed, should be "github.com/vaporz/turbo".
https://vaporz.github.io/master/en/index
Html pages are out of date, regenerated, thanks.

**Comment by vaporz** [comment]
> it it that I didn't get the package?

Yes, as per the doc, "git.apache.org/thrift.git/lib/go/thrift" is one of the dependency.

> I suggest change the dependency libs here:
https://github.com/apache/thrift

I tried, but it seems code generated by thrift is using "git.apache.org/thrift.git/lib/go/thrift". So I think we should also use that package, what do you think?

**Comment by lzbj** [comment]
ok, correct, I'll clone it manually, thanks.

**Comment by lzbj** [comment]
close this one.

**Comment by lzbj** [comment]
fixed by clone manually.
