### ISSUE TITLE
Does turbo support gRPC services implemented in other languages?

### ISSUE THREAD

**Issue by yifeikong** [vaporz/turbo#41]
My services are implemented in Python, could I use turbo to turn them into restful?

**Comment by vaporz** [comment]
I think you can do that.

Turbo first creates skeletons for both a HTTP server and a gRPC server(in Golang) via cmd "turbo create". After the project is created, you don't need to use this command anymore.
Then you regenerate folder "yourService/gen" via cmd "turbo generate", which is used by HTTP server.

All of Turbo's core functionalities are in the client side(HTTP server), and the client makes RPC calls via gRPC, which means it doesn't care about in what language the server side is written.
So I think you can simply replace the generated Golang server with your Python server after the project is created.

**Comment by vaporz** [comment]
Hi, @yifeikong 
Is your problem solved?

PS: Turbo now supports service multiplexing.

**Comment by vaporz** [comment]
Hi, you're welcome, and I have some suggestions.
This approach should work well for internal usage, I don't know your usage scenario, but if you want to expose your APIs to external users, I doubt whether it's a good idea to bind API URL directly with service definition.

**Comment by yifeikong** [comment]
Thanks for you comment, I think the biggest challenge for my solution would be performance :p 

The restful api is for internal usage only.
