### ISSUE TITLE
按照文档增加拦截器提示component不存在，请问是什么原因呢

### ISSUE THREAD

**Issue by leonarddong** [vaporz/turbo#44]
error message:panic: no such component: LogInterceptor, forget to register?

components.go中按照文档说明增加注册方法
func RegisterComponents(s *turbo.GrpcServer){
	s.RegisterComponent("LogInterceptor", i.LogInterceptor{})
}

**Comment by vaporz** [comment]
Hi,
请改为`s.RegisterComponent("Log", i.LogInterceptor{})`试一试，名字里不用加“Interceptor”

**Comment by vaporz** [comment]
Hi,
文档已经更新：https://vaporz.github.io/master/zh/interceptor.html
如果你使用的是master分支最新的代码，请在生成的文件`grpcapi/component/components.go`中，用下面的代码注册组件：
```
func (i *ServiceInitializer) InitService(s turbo.Servable) error {
    s.ServerField().RegisterComponent("LogInterceptor", interceptor.LogInterceptor{})
    return nil
}
```

**Comment by leonarddong** [comment]
肥肠感谢~
