### ISSUE TITLE
go-module surport

### ISSUE THREAD

**Issue by fly-potato-100** [vaporz/turbo#45]
Release go-module support as soon,plz~~~ ORZ

**Comment by vaporz** [comment]
👌I'll try to do that, tonight. Or you can create a PR on this if you would like to.

**Comment by vaporz** [comment]
Hi, @fly-potato-100 , why do you need go-module support?  
Turbo creates a project(or you can create one manually), then you decide how to manage dependencies, for example, using vendor or modules.  
Either way, how Turbo manages dependencies should not be a problem to you.

**Comment by vaporz** [comment]
go modules supported at v0.4.0
