### ISSUE TITLE
turbo create at windows  error

### ISSUE THREAD

**Issue by bobac-small** [vaporz/turbo#47]
$ turbo create demo DemoService -r grpc
panic: open D/src/D/src/demo/service.yaml: The system cannot find the file specified.

goroutine 1 [running]:
github.com/vaporz/turbo.panicIf(...)
        D:/goWorkspace/src/github.com/vaporz/turbo/util.go:38
github.com/vaporz/turbo.(*Config).loadServiceConfig(0xc00014c3c0)

**Comment by vaporz** [comment]
Hi @bobac-small ,
What is your "GOPATH"?
Turbo will create a config file at `GOPATH/src/[PkgPath]/service.yaml`, then read this file.
In your case, "demo" is `[PkgPath]`, and "D/src/D" seems like your `GOPATH`?

**Comment by bobac-small** [comment]
有办法指定当前目录？？？

**Comment by vaporz** [comment]
目前不能，因为在go module出来之前，代码必须放在GOPATH下面

**Comment by bobac-small** [comment]
好的，tks
发自我的iPhone

------------------ Original ------------------
