### ISSUE TITLE
win10 turbo create error

### ISSUE THREAD

**Issue by luyingjie** [vaporz/turbo#48]
panic: open C/src/C/src/package/path/to/yourservice/service.yaml: The system cannot find the file specified.

**Comment by vaporz** [comment]
Hi, Turbo currently depends on "GOPATH" to work properly.
I may find some time to remove this dependency.

**Comment by vaporz** [comment]
Hi, @luyingjie 
I upgraded Turbo to support go v1.14, and removed dependencies to GOPATH.
Please download latest Turbo release 'v0.4.0', and check out the updated [docs](https://vaporz.github.io/0.4/zh/index.html).

You have to add two new items in [config file](https://vaporz.github.io/0.4/zh/config.html): `file_root_path` and `package_path`.

I'll close this issue, please reopen if you have any further questions.
