### ISSUE TITLE
服务之间调用的问题

### ISSUE THREAD

**Issue by liqiongfan** [vaporz/turbo#51]
请问怎么在服务之间进行调用？
如果采用http方式的话，这样的开销有点大，因为假设如果我在一台机器上部署了多个service，然后在多个service之间需要互相调用的话，这样的开销确实有点大，因为涉及到了 两次的http 转 grpc， 然后grpc 转 http相当于本机调用本机的接口。

能否开放一个api，本机的service之间可以互相调用，两台机器之间通过http方式

**Comment by vaporz** [comment]
一个service是同时开放了grpc端口和http端口的，也就是service.yaml里定义的“http_port”和“grpc_service_port”，所以grpc service 之间是可以直接调grpc接口的。调grpc service时候并没有什么不同，turbo只是在grpc基础上加了个http server而已。
