### ISSUE TITLE
turbo命令创建服务的问题

### ISSUE THREAD

**Issue by liqiongfan** [vaporz/turbo#52]
使用 `turbo generate package/Service -r grpc -I path`
让其使用 xxx.proto 文件创建后，其创建的 gen/proto/grpcswitcher.go 文件 import 引入处会使用 g 引入绝对路径，这个没有使用 mod 名，导致每次都需要手工修正。

**Comment by vaporz** [comment]
g后面的内容具体是什么？是用master最新版本的代码build的turbo命令吗？
生成的格式是 `g "{{.PkgPath}}/gen/proto"`， “PkgPath”在你这个case里就是“package/Service”。
另外package path建议都是小写字母。

**Comment by liqiongfan** [comment]
这个在我这里不是package/Service 而是绝对路径------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Xiao&amp;nbsp;Zhang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月30日(星期天) 下午3:05
收件人:&nbsp;&quot;vaporz/turbo&quot;<turbo@noreply.github.com&gt;;
抄送:&nbsp;&quot;Terry Fei&quot;<774542602@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vaporz/turbo] turbo命令创建服务的问题 (#52)

**Comment by vaporz** [comment]
是什么样的绝对路径？方便把那一行的内容给我看下吗？

**Comment by liqiongfan** [comment]
就是/Users/join/Desktop/order 现在的版本可以复现呀------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Xiao&amp;nbsp;Zhang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月30日(星期天) 下午4:40
收件人:&nbsp;&quot;vaporz/turbo&quot;<turbo@noreply.github.com&gt;;
抄送:&nbsp;&quot;Terry Fei&quot;<774542602@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vaporz/turbo] turbo命令创建服务的问题 (#52)

**Comment by vaporz** [comment]
虽然可以复现，但因为我不是在Windows下开发的，所以并不知道你是如何复现的。
反馈问题时，还是希望尽量描述清楚，问题是什么，现象是什么，如何复现，运行环境是什么，最好加上日志之类的数据。
谢谢。

**Comment by liqiongfan** [comment]
我这个是mac平台  Turbo版本0.4 执行 turbo generate Order -r grpc -p ~/order出现的问题，导致无法执行 go build命令，提示/Users/join/Order/Order/gen/proto不在GOROOT里面，因为我是使用go mod 所以不应该发生这个问题。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Xiao&amp;nbsp;Zhang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月30日(星期天) 晚上6:30
收件人:&nbsp;&quot;vaporz/turbo&quot;<turbo@noreply.github.com&gt;;
抄送:&nbsp;&quot;Terry Fei&quot;<774542602@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vaporz/turbo] turbo命令创建服务的问题 (#52)

**Comment by vaporz** [comment]
1，generate命令没有-p参数，可能是你的笔误。
2，package name 请不要使用大写字母：[They are lower case, with no under_scores or mixedCaps.](https://blog.golang.org/package-names)。修改package name时，别忘了同时修改service.yaml中的“package_path”。
3，所以我还是不知道你的grpcswitcher.go 文件中，g那一行的内容到底是什么，如果是`g "Order/gen/proto"`，那么至少生成代码是没有问题的，就像你代码里其他地方会用到“Order/grpcservice/impl”这个package一样。试试把“Order”改成“order”，再把两个环境变量“GOPATH”和“GOROOT”删掉？

**Comment by liqiongfan** [comment]
默认情况下：使用命令：
`turbo create order Order -r grpc -p ~/Desktop` 生成的代码没问题。
但是修改了 proto的定义文件后，使用如下命令：
`turbo generate order -r grpc -I ~/Desktop/order`

然后生成的 `grpcswitcher.go` 文件的第五行是绝对路径：
```
import (
	g "/Users/josin/Desktop/order/gen/proto"
	"github.com/vaporz/turbo"
	"net/http"
	"errors"
)
```

而不是 

```
import (
	g "order/gen/proto"
	"github.com/vaporz/turbo"
	"net/http"
	"errors"
)
```

**Comment by vaporz** [comment]
明白了，我尝试在本地（Ubuntu）用下面两个命令复现问题，但没发现异常：
```
turbo create order Order -r grpc -p /mnt/d/workspace  
turbo generate order -r grpc -I /mnt/d/workspace/order/
```
出问题的那行是在generator.go的模板文件中生成的：
https://github.com/vaporz/turbo/blob/fd284c94ffe14cdae470d0c3ea58b5718b3901fc/generator.go#L92
能否麻烦您：
1， 修改本地的turbo代码，把g.PkgPath的值打印出来：fmt.Println(g.PkgPath)
2， 运行 
```
cd turbo/turbo
go install
```
安装修改后的turbo命令。
3，再次执行`turbo generate order -r grpc -I ~/Desktop/order`，然后观察打印出来的值
