### ISSUE TITLE
window下 turbo命令无法使用

### ISSUE THREAD

**Issue by ghost** [vaporz/turbo#53]
下载了 release后， 无法使用turbo命令。  是不是还需要什么设置？

**Comment by vaporz** [comment]
报的啥错误？

**Comment by vaporz** [comment]
我都是在Ubuntu下使用，你的Windows上有Windows terminal么？可以装个Ubuntu子系统

**Comment by SickoOrange** [comment]
目前应该是只支持ubuntu吧，  我在windows设置了path 也运行不了。 我这边是公司的电脑，不允许装linux 子系统

**Comment by vaporz** [comment]
windows应该也是支持的，测试过，只是我个人用Linux比较多。具体看你报的什么错误吧
