### ISSUE TITLE
java grpc可以吗?

### ISSUE THREAD

**Issue by TOP-LH** [vaporz/turbo#54]
java grpc可以吗?

**Comment by vaporz** [comment]
是说server端是java写的吗？
应该是可以的，我这个工具是针对client端，把grpc的client端包装成http的。
server端用什么语言写的都可以。

**Comment by vaporz** [comment]
如果server端是java的，那就不用管turbo生成的service文件，启动程序的时候，也只启动自动生成的grpcapi文件夹里的main函数就行
