### ISSUE TITLE
还是摆脱不了proto文件？

### ISSUE THREAD

**Issue by ryouaki** [vaporz/turbo#55]
那这个和自己写一个对应接口的rpc转http的区别是？

**Comment by vaporz** [comment]
区别就是不用自己写代码，而是自动生成的，proto文件摆脱不了吧？这是最基础的描述文件

**Comment by vaporz** [comment]
这个项目的功能类似grpc-gateway：
https://github.com/grpc-ecosystem/grpc-gateway

**Comment by ryouaki** [comment]
我最近发现 proto文件可以动态解析，不需要编译。有没有尝试过这种方式？

**Comment by vaporz** [comment]
哦，有相关资料么？很久没关注这方面的进展了
